name: Update README with Commit Hash

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Get commit hash
        shell: pwsh
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $env:GITHUB_ENV

      - name: Update README
        shell: pwsh
        run: |
          echo "Last commit: $env:COMMIT_HASH" > README.md

      - name: Commit changes
        shell: pwsh
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add README.md

          if (-not (git diff --quiet)) {
            git commit -m "Update README with commit hash [skip ci]"
            git push
          } else {
            echo "No changes"
          }