name: Update README with Commit Hash

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get commit hash
        shell: powershell
        run: |
          $hash = git rev-parse --short HEAD
          "COMMIT_HASH=$hash" >> $env:GITHUB_ENV

      - name: Update README
        shell: powershell
        run: |
          "Last commit: $env:COMMIT_HASH" | Out-File -Encoding utf8 README.md

      - name: Commit changes
        shell: powershell
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add README.md
          git diff --quiet

          if ($LASTEXITCODE -ne 0) {
            git commit -m "Update README with commit hash [skip ci]"
            git push
          } else {
            Write-Output "No changes"
          }